### ISSUE TITLE
Make the icon only toolbar selectable

### ISSUE THREAD

**Issue by petrillek** [jakubhnilicka/adminic-toolbar#1]
Hi Jakub,
I like your approach to the administration menu!

As an editor after few hours spent with the toolbar I will remember where things are and I will not need the icon + text for the first level items.

Make a switch on the toolbar which can permanently (for current user) set the toolbar to icon only mode even on wide screen.

**Comment by jakubhnilicka** [comment]
Introduced in alpha2 release. You can choose compact mode on module settings form.
