### ISSUE TITLE
White screen of death

### ISSUE THREAD

**Issue by iBobik** [jakubhnilicka/adminic-toolbar#11]
After module install Drupal works, but after enabling Adminic in user profile it will end with this error:

Uncaught PHP Exception Drupal\\Component\\Serialization\\Exception\\InvalidDataTypeException: "You cannot define a mapping item when in a sequence at line 36 (near "secondary_sections_links:")" at /var/www/drupal/web/core/lib/Drupal/Component/Serialization/YamlSymfony.php line 40, referer: http://localhost:8078/node/2

When I uninstall module by Drupal Console the Drupal will work again. When I install module back it will end with error again.

Drupal 8.5.1

**Comment by denniscohn** [comment]
Any update on this?
After I've upgraded to 8.5.1, this module doesn't work.

**Comment by jakubhnilicka** [comment]
Hi, yes, I have it solved. I will release alpha2 with this fix + themes and compact mode (#1) of toolbar during weekend.

**Comment by denniscohn** [comment]
Ok great! Thanks 👍

**Comment by jakubhnilicka** [comment]
Fixed on alpha2 release on drupal.org
