### ISSUE TITLE
Assist/help maintain

### ISSUE THREAD

**Issue by dubcanada** [jakubhnilicka/adminic-toolbar#13]
Hello Jakub,

I really love this toolbar and I am planning on using it on my Drupal sites, I'd like to help maintain it. I am wondering if you would be up for something like that?

A few things I think it needs.

- Way to turn it on by default for all users/or a specific role.
- The button system from https://www.drupal.org/files/project-images/adminic-drupal-8-theme_0.png or a way to create buttons in the yaml.
- Allow using Drupal admin menu instead of YAML.
- Allow specific roles/users to have different menus/YAMLs.

Thoughts?

**Comment by jakubhnilicka** [comment]
Hi, I will be pleased. I will create some document for sharing ideas. Maybe we can meet on slack? I'm on Drupal or Thunder slack.

Thank you

**Comment by jakubhnilicka** [comment]
Fixed in 8.x-1.0-alpha4.
