### ISSUE TITLE
Possible to add extra links like the "Admin Toolbar Extra Tools" submodule?

### ISSUE THREAD

**Issue by jakubhnilicka** [jakubhnilicka/adminic-toolbar#15]
Is it possible to have the extra menu links that the "Admin Toolbar Extra Tools"-module (a submodule of the admin toolbar module) gives us?
Really missing those extra links (flush caches, run cron, etc...) in Adminic Toolbar.

I think that will be a nice add-on for this module..
What do you think?

Yeah, those links would be great.
I would like to see to following links, but maybe you can add/leave one :)

Flush all caches
Flush CSS and Javascript
Flush plugins cache
Flush render cache
Flush routing and links cache
Flush static cache
Flush views cache
Run cron
Run updates

**Comment by dubcanada** [comment]
I miss those functions, that's for sure. Is there anyway to add sub links at this stage or is it just limited to 1 level?

Could maybe have like a sort of dropdown menu onclick of the Drupal logo and have all of those, so it is familiar to the default toolbar?

**Comment by jakubhnilicka** [comment]
Fixed in 8.x-1.0-alpha4.
