### ISSUE TITLE
How to instal it by Composer?

### ISSUE THREAD

**Issue by iBobik** [jakubhnilicka/adminic-toolbar#8]
Trying:
```
composer require drupal/adminic_toolbar
composer require jakubhnilicka/Adminic-Toolbar
```
Both not working. Will be nice to have better install instructions in README if it needs some special commands.

**Comment by n1kolas** [comment]
Hi, I did the following:

First add a new repository under "repositories" in composer.json:

```
{
    "type": "vcs",
    "url": "https://github.com/jakubhnilicka/adminic-toolbar"
}

```
Then require the package in the "require" section

`"jakubhnilicka/adminic_toolbar": "dev-devel"`

Available versions:
[dev-devel, dev-master, dev-8.x-1.x]

After that you can update your composer lock file
`composer update --lock` and `composer install`

**Comment by iBobik** [comment]
Not tried :-)

Why you do not use releases on drupal.org <http://drupal.org/> or at least register it on packagist?

**Comment by jakubhnilicka** [comment]
Hi, I created first alpha release on drupal.org. You can use `composer require 'drupal/adminic_toolbar:^1.0'` from now.
